[module-5]
StanislavTrush/jmp2017 pull request #5
Opened 2017-03-27 22:57 UTC by StanislavTrush

2017-03-28 15:31 UTC, AliaksandrPimenauAP commented on src/main/java/com/epam/jmp2017/model/json/ActionModel.java
> +    private static ConditionsLoader conditionsLoader;
Why static?

2017-03-28 15:33 UTC, AliaksandrPimenauAP commented on src/main/java/com/epam/jmp2017/util/loaders/ConditionsLoader.java
> +    public void setPath(String path) {
Use @Required annotation

2017-03-28 15:35 UTC, AliaksandrPimenauAP commented on src/main/webapp/WEB-INF/mvc-dispatcher-servlet.xml
> +    <bean id="conditionsLoader" class="com.epam.jmp2017.util.loaders.ConditionsLoader" init-method="cacheConditions">
Use singleton scope

2017-03-28 15:37 UTC, StanislavTrush commented on src/main/java/com/epam/jmp2017/model/json/ActionModel.java
> +    private static ConditionsLoader conditionsLoader;
Otherwise Gson goes in cyclic initializations and produce StackOverflowException

2017-03-28 15:37 UTC, StanislavTrush commented on src/main/webapp/WEB-INF/mvc-dispatcher-servlet.xml
> +    <bean id="conditionsLoader" class="com.epam.jmp2017.util.loaders.ConditionsLoader" init-method="cacheConditions">
singleton is default scope

2017-03-28 15:38 UTC, AliaksandrPimenauAP commented on src/main/java/com/epam/jmp2017/controller/MainController.java
> +	private ConditionsLoader conditionsLoader;
Use alias "loader"

2017-03-28 15:38 UTC, AliaksandrPimenauAP commented on src/main/java/com/epam/jmp2017/model/conditions/CompositeCondition.java
> +    private ConditionsLoader conditionsLoader;
Use alias "loader"

2017-03-28 15:38 UTC, AliaksandrPimenauAP commented on src/main/java/com/epam/jmp2017/model/json/ActionModel.java
> +    private static ConditionsLoader conditionsLoader;
Use alias "loader"

2017-03-28 15:42 UTC, AliaksandrPimenauAP requested changes
Please, fix all issues

2017-03-28 15:50 UTC, AliaksandrPimenauAP commented on src/main/webapp/WEB-INF/mvc-dispatcher-servlet.xml
> +    <bean id="conditionsLoader" class="com.epam.jmp2017.util.loaders.ConditionsLoader" init-method="cacheConditions">
Explicit declaration will make this bean recognizable. At least you will think a bit before changing scope for this bean (for ex. during refactoring).

2017-04-02 16:58 UTC, StanislavTrush commented
All fixed

2017-04-02 16:59 UTC, merged